version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: zai-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zai-db
    ports:
      - "5432:5432"
    volumes:
      - zai-db-data:/var/lib/postgresql/data

volumes:
  zai-db-data:
